[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing - return index.html for all paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = ["en"]}

# For Single Page Applications. Get all /*.html requests to return the root /index.html
[[redirects]]
  from = "/*.html"
  to = "/index.html"
  status = 200

# For any other direct file requests, serve them as is
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"
